/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as FeedDotjsonRouteImport } from './routes/feed[.]json'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProfileRouteImport } from './routes/api/profile'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotjsonRoute = FeedDotjsonRouteImport.update({
  id: '/feed.json',
  path: '/feed.json',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/feed.json': typeof FeedDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/profile': typeof ApiProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/feed.json' | '/sitemap.xml' | '/api/profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/feed.json' | '/sitemap.xml' | '/api/profile'
  id: '__root__' | '/' | '/feed.json' | '/sitemap.xml' | '/api/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeedDotjsonRoute: typeof FeedDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiProfileRoute: typeof ApiProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.json': {
      id: '/feed.json'
      path: '/feed.json'
      fullPath: '/feed.json'
      preLoaderRoute: typeof FeedDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeedDotjsonRoute: FeedDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiProfileRoute: ApiProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
